"""Generated by scripts/host_manifest.py; host route identity."""

from __future__ import annotations

HOST_MANIFEST_SHA256 = (
    "9464e911860ab334756b9cdc95ce93bb1b87b692b71da21c514d7165a718e529"
)
