-- N27's remainder: a line of a PDF whose glyphs are painted in a colorant
-- that paints nothing -- a Separation's `None` (ISO 32000-1, 8.6.6.4), or a
-- DeviceN whose colorants all are (8.6.6.5) -- is marked `colorant_none`,
-- beside 0040's five reasons. The checks are widened to every sorted
-- combination of the six; every row already stored holds one of 0040's
-- thirty-one, which stay, and nothing stored changes.
ALTER TABLE source_tokens DROP CONSTRAINT source_tokens_hidden_check;
ALTER TABLE source_tokens ADD CONSTRAINT source_tokens_hidden_check
    CHECK (hidden IN (
        'colorant_none', 'colorant_none,near_background',
        'colorant_none,near_background,optional_content_off',
        'colorant_none,near_background,optional_content_off,painted_over',
        'colorant_none,near_background,optional_content_off,painted_over,render_mode_3',
        'colorant_none,near_background,optional_content_off,painted_over,render_mode_3,under_2pt',
        'colorant_none,near_background,optional_content_off,painted_over,under_2pt',
        'colorant_none,near_background,optional_content_off,render_mode_3',
        'colorant_none,near_background,optional_content_off,render_mode_3,under_2pt',
        'colorant_none,near_background,optional_content_off,under_2pt',
        'colorant_none,near_background,painted_over',
        'colorant_none,near_background,painted_over,render_mode_3',
        'colorant_none,near_background,painted_over,render_mode_3,under_2pt',
        'colorant_none,near_background,painted_over,under_2pt',
        'colorant_none,near_background,render_mode_3',
        'colorant_none,near_background,render_mode_3,under_2pt',
        'colorant_none,near_background,under_2pt', 'colorant_none,optional_content_off',
        'colorant_none,optional_content_off,painted_over',
        'colorant_none,optional_content_off,painted_over,render_mode_3',
        'colorant_none,optional_content_off,painted_over,render_mode_3,under_2pt',
        'colorant_none,optional_content_off,painted_over,under_2pt',
        'colorant_none,optional_content_off,render_mode_3',
        'colorant_none,optional_content_off,render_mode_3,under_2pt',
        'colorant_none,optional_content_off,under_2pt', 'colorant_none,painted_over',
        'colorant_none,painted_over,render_mode_3',
        'colorant_none,painted_over,render_mode_3,under_2pt',
        'colorant_none,painted_over,under_2pt', 'colorant_none,render_mode_3',
        'colorant_none,render_mode_3,under_2pt', 'colorant_none,under_2pt',
        'near_background', 'near_background,optional_content_off',
        'near_background,optional_content_off,painted_over',
        'near_background,optional_content_off,painted_over,render_mode_3',
        'near_background,optional_content_off,painted_over,render_mode_3,under_2pt',
        'near_background,optional_content_off,painted_over,under_2pt',
        'near_background,optional_content_off,render_mode_3',
        'near_background,optional_content_off,render_mode_3,under_2pt',
        'near_background,optional_content_off,under_2pt',
        'near_background,painted_over', 'near_background,painted_over,render_mode_3',
        'near_background,painted_over,render_mode_3,under_2pt',
        'near_background,painted_over,under_2pt', 'near_background,render_mode_3',
        'near_background,render_mode_3,under_2pt', 'near_background,under_2pt',
        'optional_content_off', 'optional_content_off,painted_over',
        'optional_content_off,painted_over,render_mode_3',
        'optional_content_off,painted_over,render_mode_3,under_2pt',
        'optional_content_off,painted_over,under_2pt',
        'optional_content_off,render_mode_3',
        'optional_content_off,render_mode_3,under_2pt',
        'optional_content_off,under_2pt', 'painted_over', 'painted_over,render_mode_3',
        'painted_over,render_mode_3,under_2pt', 'painted_over,under_2pt',
        'render_mode_3', 'render_mode_3,under_2pt', 'under_2pt'
    ));
ALTER TABLE source_blocks DROP CONSTRAINT source_blocks_hidden_check;
ALTER TABLE source_blocks ADD CONSTRAINT source_blocks_hidden_check
    CHECK (hidden IN (
        'colorant_none', 'colorant_none,near_background',
        'colorant_none,near_background,optional_content_off',
        'colorant_none,near_background,optional_content_off,painted_over',
        'colorant_none,near_background,optional_content_off,painted_over,render_mode_3',
        'colorant_none,near_background,optional_content_off,painted_over,render_mode_3,under_2pt',
        'colorant_none,near_background,optional_content_off,painted_over,under_2pt',
        'colorant_none,near_background,optional_content_off,render_mode_3',
        'colorant_none,near_background,optional_content_off,render_mode_3,under_2pt',
        'colorant_none,near_background,optional_content_off,under_2pt',
        'colorant_none,near_background,painted_over',
        'colorant_none,near_background,painted_over,render_mode_3',
        'colorant_none,near_background,painted_over,render_mode_3,under_2pt',
        'colorant_none,near_background,painted_over,under_2pt',
        'colorant_none,near_background,render_mode_3',
        'colorant_none,near_background,render_mode_3,under_2pt',
        'colorant_none,near_background,under_2pt', 'colorant_none,optional_content_off',
        'colorant_none,optional_content_off,painted_over',
        'colorant_none,optional_content_off,painted_over,render_mode_3',
        'colorant_none,optional_content_off,painted_over,render_mode_3,under_2pt',
        'colorant_none,optional_content_off,painted_over,under_2pt',
        'colorant_none,optional_content_off,render_mode_3',
        'colorant_none,optional_content_off,render_mode_3,under_2pt',
        'colorant_none,optional_content_off,under_2pt', 'colorant_none,painted_over',
        'colorant_none,painted_over,render_mode_3',
        'colorant_none,painted_over,render_mode_3,under_2pt',
        'colorant_none,painted_over,under_2pt', 'colorant_none,render_mode_3',
        'colorant_none,render_mode_3,under_2pt', 'colorant_none,under_2pt',
        'near_background', 'near_background,optional_content_off',
        'near_background,optional_content_off,painted_over',
        'near_background,optional_content_off,painted_over,render_mode_3',
        'near_background,optional_content_off,painted_over,render_mode_3,under_2pt',
        'near_background,optional_content_off,painted_over,under_2pt',
        'near_background,optional_content_off,render_mode_3',
        'near_background,optional_content_off,render_mode_3,under_2pt',
        'near_background,optional_content_off,under_2pt',
        'near_background,painted_over', 'near_background,painted_over,render_mode_3',
        'near_background,painted_over,render_mode_3,under_2pt',
        'near_background,painted_over,under_2pt', 'near_background,render_mode_3',
        'near_background,render_mode_3,under_2pt', 'near_background,under_2pt',
        'optional_content_off', 'optional_content_off,painted_over',
        'optional_content_off,painted_over,render_mode_3',
        'optional_content_off,painted_over,render_mode_3,under_2pt',
        'optional_content_off,painted_over,under_2pt',
        'optional_content_off,render_mode_3',
        'optional_content_off,render_mode_3,under_2pt',
        'optional_content_off,under_2pt', 'painted_over', 'painted_over,render_mode_3',
        'painted_over,render_mode_3,under_2pt', 'painted_over,under_2pt',
        'render_mode_3', 'render_mode_3,under_2pt', 'under_2pt'
    ));
