"""Generate the CP-CF authority manifest and its compiled pin; never edit vendor."""

from __future__ import annotations

import sys
from hashlib import sha256
from json import dumps
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def generate_host_manifest(root: Path = ROOT) -> bytes:
    """Exact skill/calculator source digests, in the vendor's record shape."""
    files = {
        "SKILL.md": root / "icm/stages/cp-cf/references/SKILL.md",
        "scripts/cash_flow.py": root / "caos/calculators/cash_flow.py",
    }
    hashes = {name: _entry(path) for name, path in files.items()}
    # The host's own prompt blocks, every one (F67), under their own key: the
    # instruction layer of every prompt is verified like the methodology, but
    # it is never delivered as authority the way the two files above are.
    prompts = {
        block.name: _entry(block)
        for block in sorted((root / "icm/shared/prompt").glob("*.md"))
    }
    return (
        dumps(
            {
                "module_id": "CP-CF",
                "relative_file_hashes": hashes,
                "host_prompt_hashes": prompts,
            },
            sort_keys=True,
            indent=2,
        )
        + "\n"
    ).encode()


def _entry(path: Path) -> dict[str, object]:
    data = path.read_bytes()
    return {"bytes": len(data), "sha256": sha256(data).hexdigest()}


def bundle_manifest_sha256(root: Path = ROOT) -> str:
    """The digest of the vendored bundle's own manifest, the one file it
    cannot cover (F66); compiled into `caos.methodology.bundle_pin`."""
    return sha256(
        (root / "vendor/deploy-v/DEPLOY_V_INTEGRITY_v1.json").read_bytes()
    ).hexdigest()


if __name__ == "__main__":
    raw = generate_host_manifest()
    (ROOT / "icm/HOST_INTEGRITY_v1.json").write_bytes(raw)
    (ROOT / "caos/methodology/host_pin.py").write_text(
        '"""Generated by scripts/host_manifest.py; host route identity."""\n\n'
        + 'HOST_MANIFEST_SHA256 = (\n    "'
        + sha256(raw).hexdigest()
        + '"\n)\n'
    )
    (ROOT / "caos/methodology/bundle_pin.py").write_text(
        '"""Generated by scripts/host_manifest.py; the bundle manifest pin (F66)."""'
        "\n\n"
        + 'BUNDLE_MANIFEST_SHA256 = (\n    "'
        + bundle_manifest_sha256()
        + '"\n)\n'
    )
